django_ecommerce/core/urls.py
from .views import *
from django.urls import path,include


urlpatterns = [
    # first argument is the url prefix,
    
    
]

django_ecommerce/customers/urls.py
from .views import *
from django.urls import path,include
from django.contrib.auth import views as auth_views
app_name = 'customers'

urlpatterns = [
    # first argument is the url prefix,
    path('register/', register_view, name='register'),
    path('login/', login_view, name='login'),
    path('logout/', logout_view, name='logout'),
    path('change_password/', change_password, name='change_password'),
    path('password_reset/', password_reset, name='password_reset'),
    path('user_info/', user_info, name='user_info'),
    path('profile/', profile, name='profile'),
    path('orders_list/', orders_list, name='orders_list'),
    path('last_orders/', last_orders, name='last_orders'), 
    path('order_detail/<int:order_id>/', order_detail, name='order_detail'),   
    path('user_address/', user_address, name='user_address'),   
]

django_ecommerce/django_ecommerce/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls.i18n import i18n_patterns

urlpatterns = [
    path('api/', include('core.api.urls')),
] 
urlpatterns += i18n_patterns (
    path('admin/', admin.site.urls),
    path('', include('products.urls')),
    path('orders/', include('orders.urls')),
    path('customers/', include('customers.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
) + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

django_ecommerce/orders/urls.py
from .views import *
from django.urls import path

app_name = 'orders'

urlpatterns = [
    # first argument is the url prefix,
    path('checkout/', checkout, name='checkout'),     
    path('cart/', cart, name='cart'),  
    path('payment/', payment, name='payment'),     
]

django_ecommerce/products/api/urls.py
from .views import *
from django.urls import path,include
from rest_framework import routers

app_name = 'products_api'

urlpatterns = [
    # first argument is the url prefix,
    path('products/', ProductsViewSet.as_view({'get': 'list'}), name='products'),
    path('category/', ProductsByCatViewSet.as_view({'get': 'list'}), name='category'),
    path('tag/', ProductsByTagViewSet.as_view({'get': 'list'}), name='tag'),
]

django_ecommerce/products/urls.py
from .views import *
from django.urls import path

app_name = 'products'

urlpatterns = [
    # first argument is the url prefix,
    path('', index, name='index'),
    path('change_lang', change_lang, name='change_lang'),
    path('product/<int:product_id>/', product, name='product'),
    path('products_category/<int:category_id>/', products_category, name='products_category'),
    path('products_tag/<int:tag_id>/', products_tag, name='products_tag'),
    path('products/', products, name='products'),
]

django_ecommerce/products/models.py
from django.db import models
from django.db.models.deletion import CASCADE
from django.core.validators import MinValueValidator, MaxValueValidator
from django.utils.translation import gettext_lazy as _
# Create your models here.


class Tag(models.Model):
    name = models.CharField(max_length=200, unique=True,
                            verbose_name=_('name'))

    class Meta:
        verbose_name = _('Tag')
        verbose_name_plural = _('Tags')

    def __str__(self):
        return self.name


class Category(models.Model):
    name = models.CharField(max_length=250, verbose_name=_('name'))

    class Meta:
        verbose_name = _('Category')
        verbose_name_plural = _('Categories')

    def __str__(self):
        return self.name


class Product(models.Model):
    name = models.CharField(max_length=200, unique=True,
                            verbose_name=_('name'))
    description = models.TextField(verbose_name=_('description'))
    # main image
    image = models.ImageField(upload_to='product/', verbose_name=_('image'))
    tags = models.ManyToManyField(Tag, verbose_name=_('tags'))
    category = models.ForeignKey(
        Category, on_delete=models.RESTRICT, related_name="product", verbose_name=_('category'))
    price = models.IntegerField(verbose_name=_('price'))
    stock = models.PositiveIntegerField(verbose_name=_('stock'))
    is_active = models.BooleanField(verbose_name=_('active'), default=True)
    create_date = models.DateField(
        auto_now_add=True, verbose_name=_('create date'))

    class Meta:
        verbose_name = _('Product')
        verbose_name_plural = _('Products')
        ordering = ('-create_date',)

    def __str__(self):
        return self.name

    @property
    def final_price(self):
        discounts = Discount.objects.filter(status='active')
        for discount in discounts:
            if self in discount.products.all():
                return int(self.price - (self.price * discount.percentage / 100))
        return self.price


class ProductImage(models.Model):
    # additional image
    product = models.ForeignKey(
        Product, on_delete=models.CASCADE, related_name='images', verbose_name=_('product'))
    image = models.ImageField(upload_to='product/', verbose_name=_('image'))

    class Meta:
        verbose_name = _('ProductImage')
        verbose_name_plural = _('ProductImages')

    def __str__(self):
        return self.product.name


class Discount(models.Model):
    """
    Admin can add Discount  for 
    specific or all products
    """
    percentage = models.PositiveSmallIntegerField(
        validators=[MinValueValidator(0), MaxValueValidator(100)], verbose_name=_('percentage'))
    start_date = models.DateTimeField(verbose_name=_('start date'))
    end_date = models.DateTimeField(verbose_name=_('end date'))
    products = models.ManyToManyField(
        Product, related_name='product', verbose_name=_('product'))
    status_code = (('active', _('active')),
                   ('expired', _('expired')),)
    status = models.CharField(
        max_length=50, choices=status_code, default='active', verbose_name=_('status'))

    class Meta:
        verbose_name = _('Discount')
        verbose_name_plural = _('Discounts')

    def __str__(self):
        return f"{self.percentage}%"

django_ecommerce/products/api/views.py
from rest_framework.response import Response
from rest_framework.viewsets import ModelViewSet
from rest_framework.pagination import PageNumberPagination

from products.models import *
from .serializers import *


# Create your views here.

class StandardResultsSetPagination(PageNumberPagination):
    page_size = 2
    page_size_query_param = 'page_size'
    max_page_size = 1000

class ProductsViewSet(ModelViewSet):
    queryset = Product.objects.all().order_by('-create_date')
    serializer_class = ProductSerializers
    pagination_class = StandardResultsSetPagination

class ProductsByCatViewSet(ModelViewSet):
    
    serializer_class = ProductSerializers
    pagination_class = StandardResultsSetPagination

    def get_queryset(self):
        category = self.request.GET.get('category')
        queryset = Product.objects.filter(category=category).order_by('-create_date')
        return queryset

class ProductsByTagViewSet(ModelViewSet):
    
    serializer_class = ProductSerializers
    pagination_class = StandardResultsSetPagination

    def get_queryset(self):
        tag = self.request.GET.get('tag')
        tag= Tag.objects.get(name=tag)
        queryset = Product.objects.filter(tags=tag).order_by('-create_date')
        return queryset

django_ecommerce/products/views.py
from django.shortcuts import render,redirect
from django.views import generic
from .models import *
from django.utils.translation import activate
from django.db.models import Q
# Create your views here.


def index(request):
    query = request.GET.get('q')
    if query:
        products = Product.objects.filter(
            Q(name__icontains=query) | Q(category__name__icontains=query)) 
    else:
        products = Product.objects.all()
    categories = Category.objects.all()
    tags = Tag.objects.all()
    return render(request, 'products/index.html', context={'products': products, 'categories': categories, 'tags': tags, })

def change_lang(request):
    activate(request.GET.get('lang'))
    return redirect(request.GET.get('next'))

def product(request, product_id=None):
    product = Product.objects.get(id=product_id)

    return render(request, 'products/product.html', context={'product': product})


def products_category(request, category_id):
    products = Product.objects.filter(category=category_id)
    categories = Category.objects.all()
    tags = Tag.objects.all()
    return render(request, 'products/products_list.html', context={'products': products, 'categories': categories, 'tags': tags, })


def products_tag(request, tag_id):
    products = Product.objects.filter(tags=tag_id)
    categories = Category.objects.all()
    tags = Tag.objects.all()
    return render(request, 'products/products_list.html', context={'products': products, 'categories': categories, 'tags': tags, })


def products(request):
    categories = Category.objects.all()
    tags = Tag.objects.all()
    return render(request, 'products/products_list.html', context={'categories': categories, 'tags': tags, })

django_ecommerce/products/templates/products/base.html
<!DOCTYPE html>
{% load static %}
{% load i18n %}
{% get_current_language as LANGUAGE_CODE %}
{% if LANGUAGE_CODE == 'fa'%}
<html lang="fa" dir="rtl">
{% else %}
<html lang="en" dir="ltr">
{% endif %}

<head>
    <meta charset="UTF-8">
    <link href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" rel="stylesheet">
    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
    <script src="{% static 'js/base.js' %}"></script>
    <title>{% block title %}{% endblock %}</title>
    {% block extra_head %}{% endblock %}
    {% if LANGUAGE_CODE == 'fa'%}
    <link rel="stylesheet" href="{% static 'css/base_rtl.css' %}">
    {% else %}
    <link rel="stylesheet" href="{% static 'css/base.css' %}">
    {% endif %}
</head>

<body>
    <!-- navbar-start -->

    <div class="container-fluid {% if LANGUAGE_CODE == 'fa'%}text-right{% else %}text-left{% endif %}" style="background-color: white;">
        <div class="row" style="border:darkblue solid 2px;">
            <div class="col-md-6 p-2" style="background-color: lightgray;">
                <h1>{% translate "Website Name" %} </h1>
            </div>
            <div class="col-3 p-2" style="background-color: lightgray;">
                <form class="form-inline my-2 my-lg-0" method="GET" action="{% url 'products:index' %}.">
                    <input class="form-control mr-sm-2" type="search" name="q" value="{{ request.GET.q }}" placeholder="Search" aria-label="Search">
                    <button class="btn btn-outline-secondary my-2 my-sm-0" type="submit">{% translate "search" %}</button>
                </form>
            </div>
            <div class="col-2 d-flex align-items-center" style="background-color: lightgray;">
                <a href="{% url 'products:change_lang' %}?lang=en&next=/en/{{request.path|slice:'4:'}}">{% translate "EN" %}</a>/<a href="{% url 'products:change_lang' %}?lang=fa&next=/fa/{{request.path|slice:'4:'}}">{% translate "FA" %}</a>
            </div>
            <div class="col-1" style="background-color: lightgray;">
                <svg xmlns="http://www.w3.org/2000/svg" width="64" height="64" fill=#2E86C1 class="bi bi-cart"
                    viewBox="0 0 16 16">
                    <a xlink:href="{% url 'orders:cart' %}" fill=#2E86C1>
                        <path
                            d="M0 1.5A.5.5 0 0 1 .5 1H2a.5.5 0 0 1 .485.379L2.89 3H14.5a.5.5 0 0 1 .491.592l-1.5 8A.5.5 0 0 1 13 12H4a.5.5 0 0 1-.491-.408L2.01 3.607 1.61 2H.5a.5.5 0 0 1-.5-.5zM3.102 4l1.313 7h8.17l1.313-7H3.102zM5 12a2 2 0 1 0 0 4 2 2 0 0 0 0-4zm7 0a2 2 0 1 0 0 4 2 2 0 0 0 0-4zm-7 1a1 1 0 1 1 0 2 1 1 0 0 1 0-2zm7 0a1 1 0 1 1 0 2 1 1 0 0 1 0-2z" />
                    </a>

                </svg>
            </div>

        </div>
        <div class="row" style="background-color: lightgray;border:darkblue solid 2px;">
            <div class="col-1"><a href="{% url 'products:index' %}" class="text-primary">{% translate "home" %}</a>
            </div>
            <div class="col-1">
                <a href="{% url 'products:products' %}" class="text-primary">{% translate "products"%}</a>
            </div>
            <div class="col-6"></div>
            {% if user.is_authenticated %}
            <div class="col-2"></div>
            {% if user.first_name %}

            <div class="col-1"><a href="{% url 'customers:profile' %}" class="text-primary">{{user.first_name}}
                    {{user.last_name}}</a></div>
            {% else %}
            <div class="col-1"><a href="{% url 'customers:profile' %}" class="text-primary">{% translate "profile"%}</a></div>
            {% endif %}
            <div class="col-1"><a href="{% url 'customers:logout' %}" class="text-primary">{% translate "logout"%}</a></div>
            {% else %}
            <div class="col-2"></div>
            <div class="col-1"><a href="{% url 'customers:login' %}" class="text-primary">{% translate "login"%}</a></div>
            <div class="col-1"><a href="{% url 'customers:register' %}" class="text-primary">{% translate "register"%}</a></div>
            {% endif %}
        </div>


        <div class="container-fluid p-2 " id="main" style="min-height: 70vh ; background-color: white ;">
            {% csrf_token %}
            <script>
                csrf_token = $("input[name='csrfmiddlewaretoken']").val()
                LANGUAGE_CODE = "{{LANGUAGE_CODE}}"
            </script>
            {% block content %}{% endblock %}
        </div>

    </div>

    <!-- begin:footer -->
    <div id="footer" class="bg-dark text-white {% if LANGUAGE_CODE == 'fa'%}text-right{% else %}text-left{% endif %}">
        <div class="container">
            <div class="row pt-5">
                <div class="col-6 p-2">
                    <h3>{% translate "About Me"%}</h3><br>
                    <p>{% translate "Mahdi Sijani"%}</p>

                    <p> {% translate "Maktab Sharif BootCamp 53"%} 
                        (Python Back-End Developer)</p>

                </div>
                <div class="col-2 p-2"></div>
                <div class="col-4 p-2">
                    <div class="widget">
                        <h3>{% translate "Contact us"%}</h3>
                        <address>
                            Telp. : +98-123456789<br>
                            Email : Info@gmail.com
                        </address>
                    </div>
                </div>


                <!-- begin:copyleft -->
                <div class="row">
                    <div class="col-md-12 copyleft">
                        <p> {% translate "copyright text"%}</p>

                        <a href="#top" class="btn btn-primary scroltop"><i class="fa fa-angle-up"></i></a>

                    </div>
                </div>
            </div>
        </div>
        <!-- end:footer -->
</body>



</html>

django_ecommerce/products/templates/products/index.html
{% extends 'products/base.html' %}
{% load i18n%}
{% load humanize %} 
{% block title %} {% translate "Home"%} {% endblock %}
{% block content %}
<div class="row">
    <div class="col-3 p-3">
        <div class="row">
            <div class="card side " id="categories-card" style="width: 100%;height: 100%">
                <div class="card-header side-header text-right">
                    <p class="card-text  text-right" style="font-size: 18px; margin-right: 2px">
                        {% translate "Categories"%} </p>
                </div>
                <div class="card-body">
                    <div class="row">
                        <div class="col-12">
                            <nav id="cat-column" style="direction:rtl">
                                {% for category in categories %}
                                <a href="{% url 'products:products_category' category.id %}">{{category.name}}</a><br>
                                {% endfor %}
                            </nav>
                        </div>
                    </div>
                </div>
            </div>
            <div class="card side mt-3" style="width: 100%;height: 100%">
                <div class="card-header side-header">
                    <div class="card-title  text-right">
                        <p>{% translate "Tags"%}</p>
                    </div>
                </div>
                <div class="card-body" id="body-tags">
                    {% for tag in tags %}
                    <button id="button-tag"><a href="{% url 'products:products_tag' tag.id %}">{{tag.name}}</a></button>
                    
                    {% endfor %}
                </div>
            </div>
        </div>
    </div>
    <div class="col-9 p-3">
        <div class="row ">
            {% for product in products %}
            <!-- a product -->
            <div class="col-md-3 mb-3">
                <div class="card">
                    <img class="card-img-top" src="{{product.image.url}}" alt="Card image cap">
                    <div class="card-body">
                        <a href="{% url 'products:product' product.id %}" class=" card-title stretched-link">
                            {{product.name}}
                        </a>
                        {% if product.price != product.final_price%}
                        <h3 class="card-title text-left text-muted"><del>{{product.price|intcomma}} <small>{% translate "Toman"%}</small> </del></h3> 
                        <h3 class="card-title text-left">{{product.final_price|intcomma}} <small>{% translate "Toman"%}</small> </h3>
                        {% else %}
                        <h3 class="card-title text-left">{{product.price|intcomma}} <small>{% translate "Toman"%}</small> </h3>
                        {% endif %}
                        
                    </div>
                </div>
            </div>
            <!-- /a product -->
            {% endfor %}
        </div>
    </div>

</div>

{% endblock %}

django_ecommerce/products/templates/products/product.html
{% extends 'products/base.html' %}
{% load static %}
{% load i18n %}
{% load humanize %} 
{% block title %} {{product.name}}{% translate "Detail"%} {% endblock %}

{% block content %}

<div class="row p-2 border">
    <div class="col-4 border text-center p-5 m-2">
        <img src="{{product.image.url}}" class="img-fluid">
        <div class="row">
            {% for image in product.images.all %}
            <div class="col-6">
                <img src="{{image.image.url}}" class="img-thumbnail">
            </div>
            {% endfor %}
        </div>
    </div>
    <div class="col-7 border p-5 m-2">
        <h4>{{product.name}}</h4>
        <div style="min-height: 20vh;"></div>
        <h3 class=" text-left">{{product.price|intcomma}} <small>{% translate "Toman"%}</small> </h3><br>

        <input type="button" data-product="{{product.id}}" data-action="add"
            onclick="add_item(this.dataset.product,this.dataset.action)" value="{% translate 'Add to Cart'%}"
            class="btn btn-primary">


    </div>

</div>
<div class="row border mt-5">
    <div class="col-12 p-5 ">
        <h4>{% translate "Product Detail"%}</h4>
        <p>{{product.description}}</p>
    </div>
</div>
<script>
    add_to_cart_text = "{% translate 'Product added to cart successfully'%}"
</script>
<script src="{% static 'js/product.js' %}"></script>
{% endblock %}

django_ecommerce/products/templates/products/products_list.html
{% extends 'products/base.html' %}
{% load i18n %}
{% get_current_language as LANGUAGE_CODE %}
{% block title %} {% translate "products"%} {% endblock %}
{% load static %}
{% block content %}
<div class="row">
    <div class="col-3 p-3">
        <div class="row">
            <div class="card side " id="categories-card" style="width: 100%;height: 100%">
                <div class="card-header side-header text-right">
                    <p class="card-text  text-right" style="font-size: 18px; margin-right: 2px">
                        دسته‌بندی ها </p>
                </div>
                <div class="card-body">
                    <div class="row">
                        <div class="col-12">
                            <nav id="cat-column" style="direction:rtl">
                                {% for category in categories %}
                                <a onclick="get_list_by_category('{{category.id}}')">{{category.name}}</a><br>
                                {% endfor %}
                            </nav>
                        </div>
                    </div>
                </div>


            </div>
            <div class="card side mt-3" style="width: 100%;height: 100%">
                <div class="card-header side-header">
                    <div class="card-title  text-right">
                        <p>برچسب ها</p>
                    </div>
                </div>
                <div class="card-body" id="body-tags">
                    {% for tag in tags %}
                    <button id="button-tag"><a onclick="get_list_by_tag('{{tag.name}}')">{{tag.name}}</a></button>

                    {% endfor %}
                </div>

            </div>
        </div>


    </div>
    <div class="col-9 p-3">
        <!-- products container -->
        <div class="row" id="products">




        </div>
        <!-- pagination nav -->
        <nav aria-label="Page navigation example">
            <ul class="pagination d-flex justify-content-center" id="pagination_nav">

            </ul>
        </nav>
    </div>



</div>
<script>
    products_url = "{% url 'products_api:products' %}"
    cat_url = "{% url 'products_api:category' %}"
    tag_url = "{% url 'products_api:tag' %}"
    
</script>
<script src="{% static 'js/products_list.js' %}"></script>
{% endblock %}