django_ecommerce/core/urls.py
from .views import *
from django.urls import path,include


urlpatterns = [
    # first argument is the url prefix,
    
    
]

django_ecommerce/customers/api/urls.py
from .views import *
from django.urls import path,include

app_name = 'customers_api'

urlpatterns = [
    # first argument is the url prefix,
    path('register/', user_register, name='register'),
    path('change_password/', ChangePasswordView.as_view(), name='change_password'),
    path('password_reset/', include('django_rest_passwordreset.urls', namespace='password_reset')),
    path('add_address/', add_address, name='add_address'),

]

django_ecommerce/customers/urls.py
from .views import *
from django.urls import path,include
from django.contrib.auth import views as auth_views
app_name = 'customers'

urlpatterns = [
    # first argument is the url prefix,
    path('register/', register_view, name='register'),
    path('login/', login_view, name='login'),
    path('logout/', logout_view, name='logout'),
    path('change_password/', change_password, name='change_password'),
    path('password_reset/', password_reset, name='password_reset'),
    path('user_info/', user_info, name='user_info'),
    path('profile/', profile, name='profile'),
    path('orders_list/', orders_list, name='orders_list'),
    path('last_orders/', last_orders, name='last_orders'), 
    path('order_detail/<int:order_id>/', order_detail, name='order_detail'),   
    path('user_address/', user_address, name='user_address'),   
]

django_ecommerce/django_ecommerce/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls.i18n import i18n_patterns

urlpatterns = [
    path('api/', include('core.api.urls')),
] 
urlpatterns += i18n_patterns (
    path('admin/', admin.site.urls),
    path('', include('products.urls')),
    path('orders/', include('orders.urls')),
    path('customers/', include('customers.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
) + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

django_ecommerce/products/urls.py
from .views import *
from django.urls import path

app_name = 'products'

urlpatterns = [
    # first argument is the url prefix,
    path('', index, name='index'),
    path('change_lang', change_lang, name='change_lang'),
    path('product/<int:product_id>/', product, name='product'),
    path('products_category/<int:category_id>/', products_category, name='products_category'),
    path('products_tag/<int:tag_id>/', products_tag, name='products_tag'),
    path('products/', products, name='products'),
]

django_ecommerce/customers/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from django.db.models import base
from django.db.models.deletion import RESTRICT
from django.utils.translation import gettext_lazy as _
from django.core.exceptions import ValidationError
from django.dispatch import receiver
from django.urls import reverse
from django_rest_passwordreset.signals import reset_password_token_created
from django.core.mail import send_mail  
# Create your models here.


class User(AbstractUser):
    email=models.EmailField(unique=True,verbose_name=_('email'))
    mobile=models.CharField(max_length=20,null=True,blank=True,unique=True,verbose_name=_('mobile'))
    
    def clean(self):
        if self.mobile != None:
            if  (len(self.mobile) != 11) or (not(self.mobile.isnumeric())):
                raise ValidationError(
                    {'mobile': _('The mobile number is invalid')})
    def save(self, *args, **kwargs):
        self.full_clean()
        return super().save(*args, **kwargs)

class Address(models.Model):
    user = models.ForeignKey(
        User, on_delete=models.CASCADE, related_name='address',null=True,verbose_name=_('user'))
    city = models.CharField(max_length=50,verbose_name=_('city'))
    address = models.CharField(max_length=1000,verbose_name=_('address'))
    postalcode = models.CharField(max_length=10,verbose_name=_('postalcode'))

    def __str__(self):
        return f"{self.city} - {self.address}"
    
    class Meta:
       verbose_name = _('Address')
       verbose_name_plural = _('Addresses')


@receiver(reset_password_token_created)
def password_reset_token_created(sender, instance, reset_password_token, *args, **kwargs):

    email_plaintext_message = "{}?token={}".format(reverse('customers_api:password_reset:reset-password-request'), reset_password_token.key)

    send_mail(
        # title:
        "Password Reset for {title}".format(title="MY Ecommerce"),
        # message:
        email_plaintext_message,
        # from:
        "noreply@somehost.local",
        # to:
        [reset_password_token.user.email]
    )

django_ecommerce/customers/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from .models import *
from django.contrib.auth import get_user_model
# Create your views here.

User = get_user_model()
class RegisterForm(UserCreationForm):
   class Meta:
      model = User 
      fields = ('username', 'password1', 'password2',) 

class UserForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ('email','first_name','last_name','mobile',)


class AddressForm(forms.ModelForm):
    class Meta:
        model = Address
        exclude = ('customer',)

        
        
class CustomUserCreationForm(UserCreationForm):

    class Meta:
        model = User
        fields = ('username','email',)

django_ecommerce/customers/api/views.py
from rest_framework import status, generics
from rest_framework.views import APIView
from rest_framework import mixins, generics
from rest_framework.decorators import api_view, permission_classes
from django.http import Http404
from rest_framework.response import Response
from rest_framework import permissions
from customers.models import *
from .serializers import *
from rest_framework.permissions import IsAuthenticated
from django.contrib.auth import get_user_model
from rest_framework import generics

# Create your views here.

User = get_user_model()
@api_view(['POST'])
def user_register(request):
    """Create a new User and Customer"""
    register_serializer = RegisterSerializers(data=request.data)
    if register_serializer.is_valid():
        register_serializer.save()
        return Response(register_serializer.data, status=status.HTTP_201_CREATED)
    return Response(register_serializer.errors, status=status.HTTP_400_BAD_REQUEST)

class ChangePasswordView(APIView):
    """Change logged in User password"""
    permission_classes = (IsAuthenticated,)
    def get_object(self):
        return self.request.user

    def post(self, request,):
        user = self.get_object()
        serializer = ChangePasswordSerializer(user, data=request.data)
        if serializer.is_valid():
            user.set_password(serializer.validated_data['password'])
            user.save()
            return Response(serializer.data, status=status.HTTP_200_OK)
        return Response(serializer.errors, status=status.HTTP_400_BAD_REQUEST)


@api_view(['POST'])
@permission_classes([IsAuthenticated])
def add_address(request):
    """Add New address for Current Customer"""
    address_serializer = AddressSerializers(data=request.data)
    if address_serializer.is_valid():
        address = address_serializer.save()
        address.user = request.user
        address.save()
        return Response(address_serializer.data, status=status.HTTP_201_CREATED)
    return Response(address_serializer.errors, status=status.HTTP_400_BAD_REQUEST)

django_ecommerce/customers/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.contrib.auth.forms import AuthenticationForm, UserCreationForm
from .forms import *
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from django.contrib.auth import get_user_model
from django.contrib import messages
from orders.models import Order
from orders.utils import cart_sync
import datetime
from django.utils.translation import gettext as _
# Create your views here.

User = get_user_model()


def register_view(request):
    """Just render registration page"""

    registerForm = RegisterForm(request.POST)
    return render(request, 'customers/register.html', context={'registerForm': registerForm, })


def login_view(request):
    """Login user and sync cart"""
    
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')
        user = authenticate(request, username=username, password=password)
        if user is not None:
            login(request, user)
            cart_sync(request)
            
            if request.POST.get('next') :
                print(request.POST.get('next'))
                return redirect(request.POST.get('next'))
            return redirect("customers:profile")
        messages.error(request, _('username or password is wrong!'), 'danger')
    return render(request, 'customers/login.html')


def logout_view(request):
    logout(request)
    return redirect('products:index')

@login_required(login_url='customers:login')
def change_password(request):

    return render(request, 'customers/change_password.html')


def password_reset(request):

    return render(request, 'customers/password_reset.html')

@login_required(login_url='customers:login')
def user_info(request):
    """Show and edit user information """
    userForm = UserForm(instance=request.user)
    if request.method == 'POST':
        userForm = UserForm(request.POST, instance=request.user)
        if userForm.is_valid()  :
            userForm.save()
            messages.success(request, _('Your information has been successfully changed'))    

    return render(request, 'customers/user_info.html', context={'userForm': userForm})

@login_required(login_url='customers:login')
def profile(request):

    return render(request, 'customers/profile.html')

@login_required(login_url='customers:login')
def orders_list(request):
    orders = Order.objects.filter(user=request.user)
    context = {'orders': orders}
    return render(request, 'customers/orders_list.html', context)

@login_required(login_url='customers:login')
def last_orders(request):
    """Return user's last orders (10 days) orders """
    orders = Order.objects.filter(user=request.user,
                                  date__gt=datetime.datetime.today()-datetime.timedelta(days=10))
    context = {'orders': orders}
    return render(request, 'customers/orders_list.html', context)

@login_required(login_url='customers:login')
def user_address(request):
    """Return user's addresses  """
    addresses = Address.objects.filter(user=request.user)
    #form for add new address
    addressForm = AddressForm()
    context = {'addresses': addresses, 'addressForm': addressForm}

    return render(request, 'customers/user_address.html', context)

@login_required(login_url='customers:login')
def order_detail(request,order_id):
    order = get_object_or_404(Order, pk=order_id)
    context = {'order': order}
    return render(request, 'customers/order_detail.html', context)

django_ecommerce/customers/templates/customers/change_password.html
{% extends 'customers/profile_base.html' %}
{% load static %}
{% load i18n%}
{% block title %}  {% translate "Change Password"%} {% endblock %}

{% block profile_content %}

<div class="row">
    <div class="col mx-auto">
        <div class="card mx-auto text-center my-5" style="border-radius: 25px; width: 50vw;  box-shadow: 0 0.5rem 1rem 0 rgba(0, 0, 0, 0.1);
        font-size: 1.4vw;">
            <form id="change_password_form" action="" enctype="multipart/form-data" class="form-signin p-3">
                {% csrf_token %}
                <div class="form-row">
                    <div class="form-group col-md-6 mb-0">
                        <label for="old_password" class="my-4">{% translate "Old Password"%}: </label><br>
                        <input type="password" name="old_password" id="old_password"><br>
                    </div>
                    <div class="form-group col-md-6 mb-0">

                    </div>
                    <div class="form-group col-md-6 mb-0">
                        <label for="password" class="my-4"> {% translate "New Password"%}: </label><br>
                        <input type="password" name="password" id="password"><br>
                    </div>
                    <div class="form-group col-md-6 mb-0">
                        <label for="password2" class="my-4"> {% translate "Repeat New Password"%}: </label><br>
                        <input type="password" name="password2" id="password2"><br>
                    </div>
                </div>




                <input type="button" id="submit" value=" {% translate 'Change Password'%}" class="btn btn-primary my-5"
                    style="font-size: 1.2vw;">
            </form>
        </div>
    </div>
</div>

<script>
    change_password_url = "{% url 'customers_api:change_password' %}"
    change_password_text = "{% translate 'Your password changed successfully'%}"
</script>
<script src="{% static 'js/change_password.js' %}"></script>
{% endblock %}

django_ecommerce/customers/templates/customers/login.html
{% extends 'products/base.html' %}
{% load i18n%}
{% block title %} {% translate "login"%} {% endblock %}

{% block content %}

{% if messages %}
{% for message in messages %}
<div class="alert alert-{{message.tags}} text-center" role="alert">
    <h4 class="alert-heading">{{ message }} </h4>
</div>
{% endfor %}
{% endif %}
<div class="row">
    <div class="col mx-auto">
        <div class="card mx-auto text-center my-5" style="border-radius: 25px; width: 30vw;  box-shadow: 0 0.5rem 1rem 0 rgba(0, 0, 0, 0.1);
        font-size: 1.4vw;">
            <form id="login_form" method="post" action="{% url 'customers:login' %}" enctype="multipart/form-data"
                class="form-signin p-3">
                {% csrf_token %}
                <label for="username" class="my-4"> {% translate "Username"%}:</label><br>
                <input type="text" name="username"><br>
                <label for="password" class="my-4">{% translate "Password"%}:</label><br>
                <input type="password" name="password"><br>
                <a href="{% url 'customers:password_reset' %}">{% translate "Reset Password"%} </a>
                <input type="submit" id="submit" value="{% translate 'login'%}" class="btn btn-primary my-5"
                    style="font-size: 1.4vw;">
                <input type="hidden" name="next" value="{{request.GET.next  }}">
            </form>
        </div>
    </div>
</div>

{% endblock %}

django_ecommerce/customers/templates/customers/order_detail.html
{% extends 'customers/profile_base.html' %}
{% load i18n%}
{% load humanize %} 
{% block title %}{% translate "order history"%} {% endblock %}

{% block profile_content %}

<table class="table table-striped mt-5">
    <thead>
        <tr>
            <th>{% translate "product name"%}</th>
            <th>{% translate "quantity"%}</th>
            <th>{% translate "price"%}</th>
        </tr>
    </thead>

    {% for item in order.item.all %}
    <tr>
        <td>
            <a href="{% url 'products:product' item.product.id %}">{{item.product.name}}</a>
        </td>
        <td>
            {{item.quantity}}
        </td>
        <td>
            {{item.total_item_price |intcomma}}
        </td>
    </tr>

    {% endfor %}
</table>
<p>{% translate "total price"%} : {{order.total_price|intcomma}}</p>
<p>{% translate "final price"%} : {{order.final_price|intcomma}}</p>

{% endblock %}

django_ecommerce/customers/templates/customers/orders_list.html
{% extends 'customers/profile_base.html' %}
{% load i18n%}
{% block title %} {% translate "order history"%} {% endblock %}

{% block profile_content %}
{% if orders %}
<table class="table table-striped mt-5">
    <thead>
        <tr>
            <th>{% translate "order number"%}</th>
            <th>{% translate "order date"%}</th>
            <th>{% translate "status"%}</th>
            <th></th>
        </tr>
    </thead>

    {% for order in orders %}
    
        <tr>
            <td>
                {{ order.id }}
            </td>
            <td>
                {% if LANGUAGE_CODE == 'fa'%}
                {{ order.jdate }}
                {% else %}
                {{ order.date }}
                {% endif %}
            </td>
            <td>
                {% translate  order.status %}
            </td>
            <td>
                <a href="{% url 'customers:order_detail' order.id %}"> {% translate "Details"%}</a>
            </td>
        </tr>
   
    {% endfor %}
</table>


{% else %}
<p> {% translate "No Orders yet"%}</p>
{% endif %}

{% endblock %}

django_ecommerce/customers/templates/customers/password_reset.html
{% extends 'products/base.html' %}
{% load static %}
{% load i18n%}
{% block title %} {% translate 'Reset Password'%} {% endblock %}

{% block content %}

<div class="row">
    <div class="col mx-auto">
        <div class="card mx-auto text-center my-5" style="border-radius: 25px; width: 30vw; height: 60vh; box-shadow: 0 0.5rem 1rem 0 rgba(0, 0, 0, 0.1);
        font-size: 1.4vw;" id="form_container">
            <form id="password_reset_form" method="post"
                action="{% url 'customers_api:password_reset:reset-password-request' %}" enctype="multipart/form-data"
                class="form-signin p-3">
                {% csrf_token %}
                <label for="email" class="my-4">{% translate "Email"%}:</label><br>
                <input type="email" name="email"><br>
                <input type="button" id="submit" onclick="send_email()" value="{% translate 'Reset Password'%}"
                    class="btn btn-primary my-5" style="font-size: 1.4vw;">
            </form>

        </div>
    </div>
</div>
<script>
    reset_password_confirm_url = "{% url 'customers_api:password_reset:reset-password-confirm' %}"
    token_send_text = "{% translate 'Token was sent to your email'%}"
    token_text = "{% translate 'token'%}"
    new_password_text = "{% translate 'New password'%}"
    change_password_text = "{% translate 'Change password'%}"
    change_password_msg = "{% translate 'Your password changed successfully'%}"
</script>
<script src="{% static 'js/password_reset.js' %}"></script>

{% endblock %}

django_ecommerce/customers/templates/customers/profile.html
{% extends 'customers/profile_base.html' %}
{% block profile_content %}



{% endblock %}

django_ecommerce/customers/templates/customers/profile_base.html
{% extends 'products/base.html' %}
{% load i18n%}
{% block title %} {% translate 'Profile'%} {% endblock %}

{% block content %}

<div class="row">
    <div class="col-3 p-2">
        <div class="card" style="width: 18rem;">
            <div class="card-header">
                {{user.customer.first_name}} {{user.customer.last_name}}
            </div>
            <ul class="list-group list-group-flush">
                <li class="list-group-item"><a href="{% url 'customers:user_info' %}">{% translate 'Edit Info'%}</a></li>
                <li class="list-group-item"><a href="{% url 'customers:change_password' %}">{% translate "Change Password"%}</a></li>
                <li class="list-group-item"><a href="{% url 'customers:orders_list' %}">{% translate "Orders history"%}</a></li>
                <li class="list-group-item"><a href="{% url 'customers:last_orders' %}"> {% translate "Last orders"%}</a></li>
                <li class="list-group-item"><a href="{% url 'customers:user_address' %}"> {% translate 'Addresses'%} </a></li>
            </ul>
        </div>
    </div>
    <div class="col-8 p-2 ">
        {% block profile_content %}{% endblock %}
    </div>
</div>

{% endblock %}

django_ecommerce/customers/templates/customers/register.html
{% extends 'products/base.html' %}
{% load static %}
{% load i18n%}
{% block title %} {% translate 'register'%} {% endblock %}

{% block content %}

<div class="row">
    <div class="col mx-auto">
        <div class="card mx-auto text-center my-5"
        style="border-radius: 25px; width: 30vw;  box-shadow: 0 0.5rem 1rem 0 rgba(0, 0, 0, 0.1);
        font-size: 1.4vw;">
            <form id="register_form" method="post" action="{% url 'customers_api:register' %}" enctype="multipart/form-data" class="form-signin p-3">
                {% csrf_token %}
                <label for="username" class="my-4" required>{% translate 'Username'%}:</label><br>
                <input type="text" name="username"><br>
                <label for="password" class="my-4">{% translate 'Password'%}:</label><br>
                <input type="password" name="password"><br>
                <label for="email" class="my-4">{% translate 'Email'%}:</label><br>
                <input type="email" name="email"><br>
                <input type="button" id="submit" value="{% translate 'Register'%}" class="btn btn-primary my-5" style="font-size: 1.4vw;">
            </form>
        </div>
    </div>
</div>

<script>
   register_url = "{% url 'customers_api:register' %}"
   registration_msg_text = "{% translate 'Your registration was successful'%}"
</script>
<script src="{% static 'js/register.js' %}"></script>

{% endblock %}

django_ecommerce/customers/templates/customers/user_address.html
{% extends 'customers/profile_base.html' %}
{% load static %}
{% load i18n%}
{% load crispy_forms_tags %}
{% block title %} {% translate "Addresses"%} {% endblock %}

{% block profile_content %}
{% csrf_token %}
{% if addresses %}
<table class="table table-striped mt-5">
    <thead>
        <tr>
            <th>{% translate "City"%} </th>
            <th>{% translate "Address"%} </th>
            <th>{% translate "Zip Code"%}</th>
        </tr>
    </thead>

    {% for address in addresses %}
    <tr>
        <td>
            {{ address.city }}
        </td>
        <td>
            {{ address.address }}
        </td>
        <td>
            {{ address.postalcode }}
        </td>
    </tr>

    {% endfor %}
</table>


{% else %}
<p>{% translate "There is no address"%}</p>
{% endif %}

<div class="p-2">
    <div class="mt-2">
        <h4>{% translate "Add New Address"%}</h4>
    </div>
    <div class="p-2 border">
        <form action="" id="add_address_form">
            {% csrf_token %}
            <div class="form-row">
                <div class="form-group col-md-12 mb-0">
                    {{ addressForm.address|as_crispy_field }}
                </div>
                <div class="form-group col-md-8 mb-0">
                    {{ addressForm.city|as_crispy_field }}
                </div>
                <div class="form-group col-md-4 mb-0">
                    {{ addressForm.postalcode|as_crispy_field }}
                </div>
            </div>

            <input type="button" id="submit" value="{% translate 'Add Address'%} " onclick="add_address()" class="btn btn-primary my-5">
        </form>
    </div>
</div>
<script>
    add_address_url = "{% url 'customers_api:add_address' %}"
    new_address_text = "{% translate 'New address registered successfully'%}"
</script>
<script src="{% static 'js/user_address.js' %}"></script>
{% endblock %}

django_ecommerce/customers/templates/customers/user_info.html
{% extends 'customers/profile_base.html' %}
{% load crispy_forms_tags %}
{% load i18n%}
{% block profile_content %}

{% if messages %}
{% for message in messages %}
<div class="alert alert-{{message.tags}} text-center" role="alert">
    <h4 class="alert-heading">{{ message }} </h4>
</div>
{% endfor %}
{% endif %}

<div class="row">
    <div class="col mx-auto">
        <div class="card mx-auto my-5" style="border-radius: 25px; width: 50vw; ; box-shadow: 0 0.5rem 1rem 0 rgba(0, 0, 0, 0.1);
        font-size: 1.4vw;">
            <form id="register_form" method="post" action="{% url 'customers:user_info' %}" enctype="multipart/form-data"
                class="form-signin p-3">
                {% csrf_token %}
                <div class="form-row">
                    
                    <div class="form-group col-md-6 mb-0">
                        {{ userForm.first_name|as_crispy_field }}
                    </div>
                    <div class="form-group col-md-6 mb-0">
                        {{ userForm.last_name|as_crispy_field }}
                    </div>
                    <div class="form-group col-md-6 mb-0">
                        {{ userForm.email|as_crispy_field }}
                    </div>
                    <div class="form-group col-md-6 mb-0">
                        {{ userForm.mobile|as_crispy_field }}
                    </div>

                </div>

                <input type="submit" id="submit" value="{% translate 'Change Info'%}"  class="btn btn-primary my-5">
            </form>
        </div>
    </div>
</div>

{% endblock %}