django_ecommerce/core/urls.py
from .views import *
from django.urls import path,include


urlpatterns = [
    # first argument is the url prefix,
    
    
]

django_ecommerce/customers/api/urls.py
from .views import *
from django.urls import path,include

app_name = 'customers_api'

urlpatterns = [
    # first argument is the url prefix,
    path('register/', user_register, name='register'),
    path('change_password/', ChangePasswordView.as_view(), name='change_password'),
    path('password_reset/', include('django_rest_passwordreset.urls', namespace='password_reset')),
    path('add_address/', add_address, name='add_address'),

]

django_ecommerce/django_ecommerce/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls.i18n import i18n_patterns

urlpatterns = [
    path('api/', include('core.api.urls')),
] 
urlpatterns += i18n_patterns (
    path('admin/', admin.site.urls),
    path('', include('products.urls')),
    path('orders/', include('orders.urls')),
    path('customers/', include('customers.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
) + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

django_ecommerce/orders/api/urls.py
from .views import *
from django.urls import path,include
from rest_framework import routers

app_name = 'orders_api'

urlpatterns = [
    # first argument is the url prefix,
    path('use_coupon/', use_coupon, name='use_coupon'),
    path('update_item/', update_item, name='update_item'),
]

django_ecommerce/orders/urls.py
from .views import *
from django.urls import path

app_name = 'orders'

urlpatterns = [
    # first argument is the url prefix,
    path('checkout/', checkout, name='checkout'),     
    path('cart/', cart, name='cart'),  
    path('payment/', payment, name='payment'),     
]

django_ecommerce/orders/models.py
from re import T
from django.db import models
from django.db.models.deletion import CASCADE, DO_NOTHING
from django.core.validators import MinValueValidator, MaxValueValidator
from customers.models import Address, User
from products.models import Product
from django.utils.translation import gettext_lazy as _
from extensions.utils import jalali_converter
# Create your models here.


class Coupon(models.Model):
    """
    Admin can add Coupon for 
    specific or all customers
    """
    code = models.CharField(max_length=50, verbose_name=_('code'))
    percentage = models.PositiveSmallIntegerField(
        validators=[MinValueValidator(0), MaxValueValidator(100)], verbose_name=_('percentage'))
    start_date = models.DateTimeField(verbose_name=_('start_date'))
    end_date = models.DateTimeField(verbose_name=_('end_date'))
    user = models.ManyToManyField(
        User, related_name='coupon', verbose_name=_('user'))
    status_code = (('active', _('active')),
                   ('expired', _('expired')),)
    status = models.CharField(
        max_length=50, choices=status_code, default='active', verbose_name=_('status'))

    def __str__(self):
        return f"{self.percentage}%"

    class Meta:
        verbose_name = _('Coupon')
        verbose_name_plural = _('Coupons')


class Order(models.Model):
    user = models.ForeignKey(
        User, on_delete=models.RESTRICT, related_name='order', verbose_name=_('user'), null=True)
    date = models.DateTimeField(auto_now_add=True, verbose_name=_('date'))
    coupon = models.ForeignKey(
        Coupon, null=True, blank=True, on_delete=models.RESTRICT, verbose_name=_('coupon'))

    status_code = (('process', _('process')),
                   ('send', _('send')), 
                   ('deliver', _('deliver')))
    status = models.CharField(
        choices=status_code, max_length=20, default='process', verbose_name=_('status'))
    address = models.ForeignKey(
        Address, on_delete=models.RESTRICT, null=True, blank=True, verbose_name=_('address'))

    def __str__(self):
        return f"{self.id}"

    class Meta:
        verbose_name = _('Order')
        verbose_name_plural = _('Orders')
        ordering = ('-date',)

    def total_price(self):
        return sum([item.total_item_price for item in self.item.all()])

    def final_price(self):
        if self.coupon:
            return int(self.total_price() - (self.total_price() * self.coupon.percentage / 100))
        return self.total_price()

    def jdate(self):
        return jalali_converter(self.date)


class Cart(models.Model):
    user = models.OneToOneField(
        User, on_delete=CASCADE, verbose_name=_('user'), null=True)
    coupon = models.ForeignKey(
        Coupon, null=True, blank=True, on_delete=models.SET_NULL, verbose_name=_('coupon'))
    # use in cookies for add to cart without login
    device = models.CharField(max_length=200, null=True, blank=True)

    class Meta:
        verbose_name = _('Cart')
        verbose_name_plural = _('Carts')

    def __str__(self):
        return f"{self.id}"

    def total_price(self):
        return sum([item.total_item_price for item in self.item.all()])

    def final_price(self):
        if self.coupon:
            return int(self.total_price() - (self.total_price() * self.coupon.percentage / 100))
        return self.total_price()


class OrderItem(models.Model):
    order = models.ForeignKey(
        Order, on_delete=models.CASCADE, related_name='item', null=True, blank=True, verbose_name=_('order'))
    cart = models.ForeignKey(
        Cart, on_delete=models.CASCADE, related_name='item', null=True, blank=True, verbose_name=_('cart'))
    product = models.ForeignKey(
        Product, on_delete=models.RESTRICT, verbose_name=_('product'))
    quantity = models.PositiveIntegerField(
        default=0, verbose_name=_('quantity'))

    class Meta:
        verbose_name = _('OrderItem')
        verbose_name_plural = _('OrderItems')
        ordering = ('-product',)

    def __str__(self):
        return f"{self.product}"

    @property
    def total_item_price(self):
        return self.quantity * self.product.final_price


class Payment(models.Model):
    order = models.OneToOneField(
        Order, on_delete=models.RESTRICT, verbose_name=_('order'))
    payment_info = models.CharField(
        max_length=50, verbose_name=_('payment_info'))

    class Meta:
        verbose_name = _('Payment')
        verbose_name_plural = _('Payments')

    def __str__(self):
        return self.id

django_ecommerce/orders/api/views.py
from django.http.response import HttpResponse
from rest_framework.response import Response
from rest_framework.decorators import api_view
from rest_framework.views import APIView
from rest_framework import status
from orders.models import *
from .serializers import *
import json

# Create your views here.


@api_view(['POST'])
def use_coupon(request):
    """If user has coupon can use it"""
    serializer = CouponSerializers(data=request.data)
    if serializer.is_valid():
        coupon_code = serializer.data['coupon']
        # get all user's active coupons
        user_coupons = request.user.coupon.filter(status='active')
        for coupon in user_coupons:
            # check coupon code is correct
            if coupon.code == coupon_code:
                # add coupon to user's cart
                cart = request.user.cart
                cart.coupon = coupon
                cart.save()
                return Response(cart.final_price(), status=status.HTTP_200_OK)
        return Response(status=status.HTTP_406_NOT_ACCEPTABLE)
    return Response(status=status.HTTP_406_NOT_ACCEPTABLE)


@api_view(['POST'])
def update_item(request):
    """If user logged in get his cart, 
    else create a temporary customer by deviceID which store in cookie.
    Then update cart's item """
    
    serializer = AddToCartSerializers(data=request.data)
    if serializer.is_valid():
        productId = serializer.data['productId']
        action = serializer.data['action']

        if request.user.is_authenticated:
            cart, created = Cart.objects.get_or_create(user=request.user)
        else:
            device = request.COOKIES['device']
            cart, created = Cart.objects.get_or_create(device=device)
        
        product = Product.objects.get(id=productId)
        orderItem, created = OrderItem.objects.get_or_create(
            cart=cart, product=product)
        if action == 'add':
            orderItem.quantity = (orderItem.quantity + 1)
        elif action == 'remove':
            orderItem.quantity = (orderItem.quantity - 1)
        orderItem.save()

        if orderItem.quantity <= 0:
            orderItem.delete()
        return Response('Item was added', status=status.HTTP_200_OK)
    return Response(status=status.HTTP_400_BAD_REQUEST)

django_ecommerce/orders/views.py
from django.http.response import JsonResponse
from django.shortcuts import render, get_object_or_404, redirect
from .models import *
from customers.forms import AddressForm
from django.views.decorators.csrf import csrf_exempt
import json
import datetime
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from django.utils.translation import gettext as _
from django.contrib.auth import get_user_model
# Create your views here.
User = get_user_model()

def cart(request):
    """If user logged in get his cart, 
    else create a temporary cart by deviceID which store in cookie."""
    try:
        cart, created = Cart.objects.get_or_create(user=request.user)
    except:
        device = request.COOKIES['device']
        cart, created = Cart.objects.get_or_create(device=device)

    for item in cart.item.all():
        if item.product.stock < item.quantity:
            messages.warning(request, _("Only {} of {} remain.").format(item.product.stock,item.product.name))
    context = {'cart': cart}
    return render(request, 'orders/cart.html', context)


@login_required(login_url='customers:login')
def checkout(request):
    """Get user's cart and address and cretae a new order"""
    cart = Cart.objects.get(user=request.user)
    for item in cart.item.all():
            if item.product.stock < item.quantity:
                return redirect("orders:cart")
    
    if request.method == 'POST':
        
        try:
            address_id = request.POST['address_id']
            address = Address.objects.get(id=address_id)
            
            order = Order.objects.create(
                user=request.user, address=address)
            
            # add coupon to order
            order.coupon = cart.coupon
            order.save()
            # put cart item to order
            for item in cart.item.all():
                item.product.stock -= item.quantity
                item.product.save()
                if item.product.stock <= 0:
                    item.product.is_active = False
                item.order = order
                item.cart = None
                item.save()
            cart.delete()
            Payment.objects.create(order=order, payment_info='123456789')
            return redirect("orders:payment")

        except:
            messages.error(
                request, _('Select an Address'), 'danger')
    cart = Cart.objects.get(user=request.user)
    addresses = Address.objects.filter(user=request.user)
    addressForm = AddressForm()
    context = {'cart': cart, 'addresses': addresses,
               'addressForm': addressForm}
    return render(request, 'orders/checkout.html', context)


@login_required(login_url='customers:login')
def payment(request):
    messages.success(request, _('Your order has been successfully submitted'))
    return render(request, 'orders/payment.html')

django_ecommerce/orders/templates/orders/cart.html
{% extends 'products/base.html' %}
{% load static %}
{% load i18n%}
{% load humanize %} 
{% block title %} {% translate "Cart"%} {% endblock %}

{% block content %}
{% if messages %}
{% for message in messages %}
<div class="alert alert-{{message.tags}} text-center" role="alert">
    <h4 class="alert-heading">{{ message }} </h4>
</div>
{% endfor %}
{% endif %}
{% if cart.item.all %}
<div class="row p-2">
    <div class="col-7 p-2">
        <div class="row">
            {% for item in cart.item.all %}
            <div class="col-12  p-2 border">
                <div class="row ">
                    <div class="col-3">
                        <img src="{{item.product.image.url}}" class="img-thumbnail"  >
                    </div>
                    <div class="col-9">
                        <h4>{{item.product.name}}</h4>
                        <div class="col"> <a data-product="{{item.product.id}}" data-action="remove" onclick="update_item(this.dataset.product,this.dataset.action)">-</a><a class="border">{{item.quantity}}</a><a data-product="{{item.product.id}}" data-action="add" onclick="update_item(this.dataset.product,this.dataset.action)">+</a> </div>
                        <p>{% translate "Price"%}:{{item.total_item_price|intcomma}}{% translate "Toman"%}</p>
                    </div>
                </div>
            </div>
            {% endfor %}
        </div>
    </div>
    <div class="col-1"></div>
    <div class="col-3 p-2">
        <div class=" row border">
            <div class="col-12 p-2">
                <h4>{% translate "Total Price"%}:</h4>
                <h4 > {{cart.total_price|intcomma}} {% translate "Toman"%}</h4>
                <a href="{% url 'orders:checkout' %}" class="btn btn-primary">{% translate "Checkout"%}  </a><br><br>
            </div>


        </div>
    </div>
</div>
<script src="{% static 'js/cart.js' %}"></script>
{% else %}
<p>{% translate "Your Cart is empty"%}</p>
{% endif %}

{% endblock %}

django_ecommerce/orders/templates/orders/checkout.html
{% extends 'products/base.html' %}
{% load static %}
{% load i18n%}
{% load humanize %} 
{% load crispy_forms_tags %}
{% block title %} {% translate "Checkout"%} {% endblock %}
{% block content %}

{% if messages %}
{% for message in messages %}
<div class="alert alert-{{message.tags}} text-center" role="alert">
    <h4 class="alert-heading">{{ message }} </h4>
</div>
{% endfor %}
{% endif %}

{% if cart.item.all %}
<div class="row p-2">
    <div class="col-7 p-2">
        <div>
            <h4>{% translate "Select your address"%}</h4>
        </div>
        {% if addresses %}
        <div class="border p-2">
            <form action="{% url 'orders:checkout' %}" id="address_form" method="POST">
                {% csrf_token %}
                <table class="table table-striped mt-5">
                    <thead>
                        <tr>
                            <th> </th>
                            <th>{% translate "City"%} </th>
                            <th>{% translate "Address"%} </th>
                            <th>{% translate "Zip Code"%}</th>
                        </tr>
                    </thead>

                    {% for address in addresses %}
                    <tr>
                        <td>
                            <input type="radio" required name="address_id" value="{{address.id}}">
                        </td>
                        <td>
                            {{ address.city }}
                        </td>
                        <td>
                            {{ address.address }}
                        </td>
                        <td>
                            {{ address.postalcode }}
                        </td>
                    </tr>

                    {% endfor %}
                </table>
            </form>
        </div>


        {% else %}
        <p>{% translate "There is no address"%}</p>
        {% endif %}
        <div class="p-2">
            <div class="mt-2">
                <h4>{% translate "Add New Address"%}</h4>
            </div>
            <div class="p-2 border">
                <form action="" id="add_address_form">
                    {% csrf_token %}
                    <div class="form-row">
                        <div class="form-group col-md-12 mb-0">
                            {{ addressForm.address|as_crispy_field }}
                        </div>
                        <div class="form-group col-md-8 mb-0">
                            {{ addressForm.city|as_crispy_field }}
                        </div>
                        <div class="form-group col-md-4 mb-0">
                            {{ addressForm.postalcode|as_crispy_field }}
                        </div>
                    </div>

                    <input type="button" id="submit" value="{% translate 'Add Address'%} " onclick="add_address()"
                        class="btn btn-primary my-5">
                </form>
            </div>
        </div>



    </div>
    <div class="col-1"></div>
    <div class="col-3 p-2">
        <div class=" row border">
            <div class="col-12 p-2">
                <form action="" id="coupon_form">
                    {% csrf_token %}
                    <label for="coupon" class="my-4">{% translate "Coupon"%}:</label><br>
                    <input type="text" name="coupon"><br>
                    <input type="button" id="submit" onclick="add_coupon()" value="{% translate 'Add Coupon'%}"
                        class="btn btn-primary my-5" style="font-size: 1vw;">
                </form>

                <h4>{% translate "Final Price"%}:</h4>
                <p id="total_price">{{cart.final_price|intcomma}}</p><br>
                <button onclick="payment()" class="btn btn-primary"> {% translate "Payment"%} </button><br><br>


            </div>
        </div>
    </div>
</div>
{% else %}
<p>{% translate "Your Cart is empty"%}.</p>
{% endif %}

<script>
    coupon_url = "{% url 'orders_api:use_coupon' %}"
    add_address_url = "{% url 'customers_api:add_address' %}"
    coupon_msg = "{% translate 'Discount code has been successfully applied'%}"
    coupon_err_msg = "{% translate 'Discount code is incorrect or expierd'%}"
    new_address_text = "{% translate 'New address registered successfully'%}"

</script>
<script src="{% static 'js/checkout.js' %}"></script>




{% endblock %}

django_ecommerce/orders/templates/orders/payment.html
{% extends 'products/base.html' %}
{% load i18n%}
{% block title %} {% translate "Payment"%} {% endblock %}
{% block content %}

{% if messages %}
{% for message in messages %}
<div class="alert alert-{{message.tags}} text-center" role="alert">
    <h4 class="alert-heading">{{ message }} </h4>
</div>
{% endfor %}
{% endif %}


{% endblock %}